spring.application.name=api

# H2 datasource
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

conexao.setDriverClassName("com.mysql.cj.jdbc.Driver");
conexao.setUrl(System.getenv("DB_URL"));
conexao.setUsername(System.getenv("DB_USER"));
conexao.setPassword(System.getenv("DB_PASSWORD"));

# H2 console
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
